fail_fast: true
repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier
        language: system
        types_or:
          - yaml
          - json5
        additional_dependencies: []
        args:
          - "--write"

      - id: ruff
        name: Ruff
        entry: uv run ruff
        args:
          - check
          - "--fix"
          - "--exit-non-zero-on-fix"
        types:
          - python
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff
        args:
          - format
          - "--force-exclude"
        language: system
        files: \.py$
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        files: \.py$
        exclude: ^tests/
